export const appTexts = {
  SIGN_UP: 'Sign Up',
  LOG_IN: 'Log in',
  OR: 'OR',
  FORGOT_PASSWORD: 'Forgot Password?',
  LOG_IN_TITLE: 'Sign in to your Account',
  REGISTER: 'Register',
  LOG_IN_DESC: 'Enter your email and password to log in',
  SIGN_UP_DESC: 'Create an account to continue!',
  CONTINUE_WITH_GOOGLE: 'Continue with Google',
  CONTINUE_WITH_APPLE: 'Continue with Apple',
  DONT_HAVE_ACCOUNT: 'Don’t have an account?',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  ACCOUNT_CREATED:
    'Account created successfully. Verification link is sent your email.',
  EMAIL_NOT_VERIFIED: 'Please verify your email before logging in',
  EMAIL_REQUIRED: 'Email Required',
  ENTER_TASK: 'Enter Task',
  PASSWORD_REQUIRED: 'Password Required',
  ENTER_NAME: 'Please enter your name',
  LOG_IN_SUCCESS: 'Logged in successfully',
  YOUR_TASKS: 'Your Tasks',
  ADD_TASK: 'Add Task',
  EDIT_TASK: 'Edit Task',
  ADD: 'Add',
  UPDATE: 'Update',
  CANCEL: 'Cancel',
  TASK_UPDATED: 'Task updated successfully!',
  TASK_ADDED: 'Task added successfully!',
  TASK_DELETED: 'Task deleted successfully!',
} as const;
